name: 'Build images'
description: 'Build images'
inputs:
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-token:
    description: 'DockerHub access token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: "./Dockerfile"
        push: true
        tags: ${{ env.BASE_IMAGE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64,darwin/amd64