on:
  push:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '0 0 * * 1'

env:
  BASE_IMAGE: ghcr.io/inventas/laravel-base:latest

jobs:
  build-backend-images:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Repository'
        uses: actions/checkout@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: inventas
          password: ${{secrets.GITHUB_TOKEN}}
      - name: "Build"
        uses: serversideup/github-action-docker-build@v5
        with:
          tags: ${{ env.BASE_IMAGE }}
          dockerfile: "./Dockerfile"
          registry: "ghcr.io"
          registry-username: inventas
          registry-token: "${{ secrets.GITHUB_TOKEN }}"
          platforms: "linux/amd64,linux/arm64"