on:
  push:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read
  packages: write

env:
  BASE_IMAGE: ghcr.io/inventas/laravel-base:latest

jobs:
  build-backend-images:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Repository'
        uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: inventas
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: "Build"
        uses: serversideup/github-action-docker-build@v5
        with:
          tags: ${{ env.BASE_IMAGE }}
          dockerfile: "./Dockerfile"
          registry: "ghcr.io"
          registry-username: inventas
          registry-token: "${{ secrets.REGISTRY_TOKEN }}"
          platforms: "linux/amd64,linux/arm/v7,linux/arm64/v8"